// Kode galat baku — sama persis dengan tabel di docs/06-kontrak-api.md.

export const KODE_GALAT = {
  TIDAK_TERAUTENTIKASI: 'TIDAK_TERAUTENTIKASI',
  OTP_SALAH: 'OTP_SALAH',
  PRODUK_TIDAK_DITEMUKAN: 'PRODUK_TIDAK_DITEMUKAN',
  EKSTRAKSI_GAGAL: 'EKSTRAKSI_GAGAL',
  BERKAS_TERLALU_BESAR: 'BERKAS_TERLALU_BESAR',
  RESEP_BELUM_LENGKAP: 'RESEP_BELUM_LENGKAP',
} as const;

export type KodeGalat = keyof typeof KODE_GALAT;
